fullname: Apery
shortname: apery
organization: coq-community
opam_name: coq-mathcomp-apery
community: true
action: true
coqdoc: false

synopsis: >-
  A formally verified proof in Coq, by computer algebra, that ζ(3) is irrational

description: |-
  This project contains a formal proof that the real number ζ(3),
  also known as Apéry's constant, is irrational. It follows roughly
  Apéry's original sketch of a proof. However, the recurrence
  relations constituting the crux of the proof have been guessed by a
  computer algebra program (in this case in Maple/Algolib). These
  relations are formally checked a posteriori, so that Coq's kernel
  remains the sole trusted code base.

publications:
- pub_url: https://arxiv.org/abs/1912.06611
  pub_title: A Formal Proof of the Irrationality of ζ(3)
- pub_url: https://hal.inria.fr/hal-00984057
  pub_title: A Computer-Algebra-Based Formal Proof of the Irrationality of ζ(3)
  pub_doi: 10.1007/978-3-319-08970-6_11
- pub_url: https://drops.dagstuhl.de/opus/volltexte/2022/16738/pdf/LIPIcs-ITP-2022-29.pdf
  pub_title: Reflexive tactics for algebra, revisited
  pub_doi: 10.4230/LIPIcs.ITP.2022.29

authors:
- name: Frédéric Chyzak
  initial: true
- name: Assia Mahboubi
  initial: true
- name: Thomas Sibut-Pinote
  initial: true

maintainers:
- name: Assia Mahboubi
  nickname: amahboubi
- name: Kazuhiko Sakaguchi
  nickname: pi8027

opam-file-maintainer: assia.mahboubi@inria.fr

opam-file-version: dev

license:
  fullname: CeCILL-C
  identifier: CECILL-C

supported_coq_versions:
  text: 8.20 or later
  opam: '{>= "8.20"}'

tested_coq_opam_versions:
- version: '2.3.0-coq-8.20'
  repo: 'mathcomp/mathcomp'
- version: '2.4.0-coq-8.20'
  repo: 'mathcomp/mathcomp'
- version: '2.4.0-rocq-prover-9.0'
  repo: 'mathcomp/mathcomp'
- version: '2.4.0-rocq-prover-dev'
  repo: 'mathcomp/mathcomp'
- version: 'coq-8.20'
  repo: 'mathcomp/mathcomp-dev'
- version: 'rocq-prover-9.0'
  repo: 'mathcomp/mathcomp-dev'
- version: 'rocq-prover-dev'
  repo: 'mathcomp/mathcomp-dev'

dependencies:
- opam:
    name: coq-mathcomp-ssreflect
    version: '{>= "2.3"}'
  description: |-
    [MathComp ssreflect](https://math-comp.github.io) 2.3 or later
- opam:
    name: coq-mathcomp-algebra
  description: |-
    [MathComp algebra](https://math-comp.github.io)
- opam:
    name: coq-mathcomp-field
  description: |-
    [MathComp field](https://math-comp.github.io)
- opam:
    name: coq-coqeal
    version: '{>= "2.1.0"}'
  description: |-
    [CoqEAL](https://github.com/coq-community/coqeal) 2.1.0 or later
- opam:
    name: coq-mathcomp-real-closed
  description: |-
    [MathComp real closed fields](https://github.com/math-comp/real-closed)
- opam:
    name: coq-mathcomp-bigenough
    version: '{>= "1.0.1"}'
  description: |-
    [MathComp bigenough](https://github.com/math-comp/bigenough) 1.0.1 or later
- opam:
    name: coq-mathcomp-zify
  description: |-
    [Mczify](https://github.com/math-comp/mczify)
- opam:
    name: coq-mathcomp-algebra-tactics
  description: |-
    [Algebra Tactics](https://github.com/math-comp/algebra-tactics)

namespace: mathcomp.apery

keywords:
- name: apery recurrence
- name: irrationality
- name: creative telescoping

categories:
- name: Mathematics/Arithmetic and Number Theory/Number theory
